//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.27 at 11:03:36 AM CET 
//


package org.sinekarta.alfresco.model.agenziaEntrate;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}DatiFornitura"/>
 *         &lt;element ref="{}DatiTitolareContabilita"/>
 *         &lt;element ref="{}DatiResponsabileConservazione"/>
 *         &lt;element ref="{}DatiDelegatoConservazione" maxOccurs="20" minOccurs="0"/>
 *         &lt;element ref="{}DatiTrasmissione"/>
 *         &lt;element ref="{}DatiArchivioInformatico"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datiFornitura",
    "datiTitolareContabilita",
    "datiResponsabileConservazione",
    "datiDelegatoConservazione",
    "datiTrasmissione",
    "datiArchivioInformatico"
})
@XmlRootElement(name = "Comunicazione")
public class Comunicazione implements Serializable {

	private static final long serialVersionUID = 1L;
	
	@XmlElement(name = "DatiFornitura", required = true)
    protected DatiFornitura datiFornitura;
    @XmlElement(name = "DatiTitolareContabilita", required = true)
    protected DatiTitolareContabilita datiTitolareContabilita;
    @XmlElement(name = "DatiResponsabileConservazione", required = true)
    protected DatiAnagrType datiResponsabileConservazione;
    @XmlElement(name = "DatiDelegatoConservazione")
    protected List<DatiAnagrType> datiDelegatoConservazione;
    @XmlElement(name = "DatiTrasmissione", required = true)
    protected DatiTrasmissione datiTrasmissione;
    @XmlElement(name = "DatiArchivioInformatico", required = true)
    protected DatiArchivioInformatico datiArchivioInformatico;

    /**
     * Gets the value of the datiFornitura property.
     * 
     * @return
     *     possible object is
     *     {@link DatiFornitura }
     *     
     */
    public DatiFornitura getDatiFornitura() {
        return datiFornitura;
    }

    /**
     * Sets the value of the datiFornitura property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiFornitura }
     *     
     */
    public void setDatiFornitura(DatiFornitura value) {
        this.datiFornitura = value;
    }

    /**
     * Gets the value of the datiTitolareContabilita property.
     * 
     * @return
     *     possible object is
     *     {@link DatiTitolareContabilita }
     *     
     */
    public DatiTitolareContabilita getDatiTitolareContabilita() {
        return datiTitolareContabilita;
    }

    /**
     * Sets the value of the datiTitolareContabilita property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiTitolareContabilita }
     *     
     */
    public void setDatiTitolareContabilita(DatiTitolareContabilita value) {
        this.datiTitolareContabilita = value;
    }

    /**
     * Gets the value of the datiResponsabileConservazione property.
     * 
     * @return
     *     possible object is
     *     {@link DatiAnagrType }
     *     
     */
    public DatiAnagrType getDatiResponsabileConservazione() {
        return datiResponsabileConservazione;
    }

    /**
     * Sets the value of the datiResponsabileConservazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiAnagrType }
     *     
     */
    public void setDatiResponsabileConservazione(DatiAnagrType value) {
        this.datiResponsabileConservazione = value;
    }

    /**
     * Gets the value of the datiDelegatoConservazione property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the datiDelegatoConservazione property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDatiDelegatoConservazione().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DatiAnagrType }
     * 
     * 
     */
    public List<DatiAnagrType> getDatiDelegatoConservazione() {
        if (datiDelegatoConservazione == null) {
            datiDelegatoConservazione = new ArrayList<DatiAnagrType>();
        }
        return this.datiDelegatoConservazione;
    }

    /**
     * Gets the value of the datiTrasmissione property.
     * 
     * @return
     *     possible object is
     *     {@link DatiTrasmissione }
     *     
     */
    public DatiTrasmissione getDatiTrasmissione() {
        return datiTrasmissione;
    }

    /**
     * Sets the value of the datiTrasmissione property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiTrasmissione }
     *     
     */
    public void setDatiTrasmissione(DatiTrasmissione value) {
        this.datiTrasmissione = value;
    }

    /**
     * Gets the value of the datiArchivioInformatico property.
     * 
     * @return
     *     possible object is
     *     {@link DatiArchivioInformatico }
     *     
     */
    public DatiArchivioInformatico getDatiArchivioInformatico() {
        return datiArchivioInformatico;
    }

    /**
     * Sets the value of the datiArchivioInformatico property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiArchivioInformatico }
     *     
     */
    public void setDatiArchivioInformatico(DatiArchivioInformatico value) {
        this.datiArchivioInformatico = value;
    }

}
