//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.27 at 11:03:36 AM CET 
//


package org.sinekarta.alfresco.model.agenziaEntrate;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Giorno"/>
 *         &lt;element ref="{}Mese"/>
 *         &lt;element ref="{}Anno"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "giorno",
    "mese",
    "anno"
})
@XmlRootElement(name = "Data")
public class Data implements Serializable {

	private static final long serialVersionUID = 1L;
	
    @XmlElement(name = "Giorno")
    protected int giorno;
    @XmlElement(name = "Mese")
    protected int mese;
    @XmlElement(name = "Anno")
    protected int anno;

    /**
     * Gets the value of the giorno property.
     * 
     */
    public int getGiorno() {
        return giorno;
    }

    /**
     * Sets the value of the giorno property.
     * 
     */
    public void setGiorno(int value) {
        this.giorno = value;
    }

    /**
     * Gets the value of the mese property.
     * 
     */
    public int getMese() {
        return mese;
    }

    /**
     * Sets the value of the mese property.
     * 
     */
    public void setMese(int value) {
        this.mese = value;
    }

    /**
     * Gets the value of the anno property.
     * 
     */
    public int getAnno() {
        return anno;
    }

    /**
     * Sets the value of the anno property.
     * 
     */
    public void setAnno(int value) {
        this.anno = value;
    }

}
