//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.27 at 11:03:36 AM CET 
//


package org.sinekarta.alfresco.model.agenziaEntrate;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Cognome"/>
 *         &lt;element ref="{}Nome"/>
 *         &lt;element ref="{}Sesso"/>
 *         &lt;element ref="{}DatiNascita"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "cognome",
    "nome",
    "sesso",
    "datiNascita"
})
@XmlRootElement(name = "DatiPersonaFisica")
public class DatiPersonaFisica implements Serializable {

	private static final long serialVersionUID = 1L;
	
    @XmlElement(name = "Cognome", required = true)
    protected String cognome;
    @XmlElement(name = "Nome", required = true)
    protected String nome;
    @XmlElement(name = "Sesso", required = true)
    protected String sesso;
    @XmlElement(name = "DatiNascita", required = true)
    protected DatiNascita datiNascita;

    /**
     * Gets the value of the cognome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCognome() {
        return cognome;
    }

    /**
     * Sets the value of the cognome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCognome(String value) {
        this.cognome = value;
    }

    /**
     * Gets the value of the nome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNome() {
        return nome;
    }

    /**
     * Sets the value of the nome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNome(String value) {
        this.nome = value;
    }

    /**
     * Gets the value of the sesso property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSesso() {
        return sesso;
    }

    /**
     * Sets the value of the sesso property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSesso(String value) {
        this.sesso = value;
    }

    /**
     * Gets the value of the datiNascita property.
     * 
     * @return
     *     possible object is
     *     {@link DatiNascita }
     *     
     */
    public DatiNascita getDatiNascita() {
        return datiNascita;
    }

    /**
     * Sets the value of the datiNascita property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiNascita }
     *     
     */
    public void setDatiNascita(DatiNascita value) {
        this.datiNascita = value;
    }

}
