//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.27 at 11:03:36 AM CET 
//


package org.sinekarta.alfresco.model.agenziaEntrate;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DatiAnagr" type="{}DatiAnagrType"/>
 *         &lt;element ref="{}FatturazioneElettronica"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "datiAnagr",
    "fatturazioneElettronica"
})
@XmlRootElement(name = "DatiTitolareContabilita")
public class DatiTitolareContabilita implements Serializable {

	private static final long serialVersionUID = 1L;
	
    @XmlElement(name = "DatiAnagr", required = true)
    protected DatiAnagrType datiAnagr;
    @XmlElement(name = "FatturazioneElettronica", required = true)
    protected String fatturazioneElettronica;

    /**
     * Gets the value of the datiAnagr property.
     * 
     * @return
     *     possible object is
     *     {@link DatiAnagrType }
     *     
     */
    public DatiAnagrType getDatiAnagr() {
        return datiAnagr;
    }

    /**
     * Sets the value of the datiAnagr property.
     * 
     * @param value
     *     allowed object is
     *     {@link DatiAnagrType }
     *     
     */
    public void setDatiAnagr(DatiAnagrType value) {
        this.datiAnagr = value;
    }

    /**
     * Gets the value of the fatturazioneElettronica property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFatturazioneElettronica() {
        return fatturazioneElettronica;
    }

    /**
     * Sets the value of the fatturazioneElettronica property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFatturazioneElettronica(String value) {
        this.fatturazioneElettronica = value;
    }

}
