//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.27 at 11:03:36 AM CET 
//


package org.sinekarta.alfresco.model.agenziaEntrate;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}LuogoConservazione"/>
 *         &lt;element ref="{}Impronta"/>
 *         &lt;element ref="{}MarcaTemporale"/>
 *         &lt;element ref="{}IndiceDocumentiInArchivio"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "luogoConservazione",
    "impronta",
    "marcaTemporale",
    "indiceDocumentiInArchivio"
})
@XmlRootElement(name = "DatiArchivioInformatico")
public class DatiArchivioInformatico implements Serializable {

	private static final long serialVersionUID = 1L;
	
    @XmlElement(name = "LuogoConservazione", required = true)
    protected LuogoConservazione luogoConservazione;
    @XmlElement(name = "Impronta", required = true)
    protected String impronta;
    @XmlElement(name = "MarcaTemporale", required = true)
    protected String marcaTemporale;
    @XmlElement(name = "IndiceDocumentiInArchivio", required = true)
    protected IndiceDocumentiInArchivio indiceDocumentiInArchivio;

    /**
     * Gets the value of the luogoConservazione property.
     * 
     * @return
     *     possible object is
     *     {@link LuogoConservazione }
     *     
     */
    public LuogoConservazione getLuogoConservazione() {
        return luogoConservazione;
    }

    /**
     * Sets the value of the luogoConservazione property.
     * 
     * @param value
     *     allowed object is
     *     {@link LuogoConservazione }
     *     
     */
    public void setLuogoConservazione(LuogoConservazione value) {
        this.luogoConservazione = value;
    }

    /**
     * Gets the value of the impronta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImpronta() {
        return impronta;
    }

    /**
     * Sets the value of the impronta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImpronta(String value) {
        this.impronta = value;
    }

    /**
     * Gets the value of the marcaTemporale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarcaTemporale() {
        return marcaTemporale;
    }

    /**
     * Sets the value of the marcaTemporale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarcaTemporale(String value) {
        this.marcaTemporale = value;
    }

    /**
     * Gets the value of the indiceDocumentiInArchivio property.
     * 
     * @return
     *     possible object is
     *     {@link IndiceDocumentiInArchivio }
     *     
     */
    public IndiceDocumentiInArchivio getIndiceDocumentiInArchivio() {
        return indiceDocumentiInArchivio;
    }

    /**
     * Sets the value of the indiceDocumentiInArchivio property.
     * 
     * @param value
     *     allowed object is
     *     {@link IndiceDocumentiInArchivio }
     *     
     */
    public void setIndiceDocumentiInArchivio(IndiceDocumentiInArchivio value) {
        this.indiceDocumentiInArchivio = value;
    }

}
