//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.27 at 11:03:36 AM CET 
//


package org.sinekarta.alfresco.model.agenziaEntrate;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}CodiceFornitura"/>
 *         &lt;element ref="{}PeriodoImposta"/>
 *         &lt;element ref="{}TipoComunicazione"/>
 *         &lt;element ref="{}ProtocolloTelematicoDaSostituire" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "codiceFornitura",
    "periodoImposta",
    "tipoComunicazione",
    "protocolloTelematicoDaSostituire"
})
@XmlRootElement(name = "DatiFornitura")
public class DatiFornitura implements Serializable {

	private static final long serialVersionUID = 1L;
	
    @XmlElement(name = "CodiceFornitura", required = true)
    protected String codiceFornitura;
    @XmlElement(name = "PeriodoImposta")
    protected int periodoImposta;
    @XmlElement(name = "TipoComunicazione")
    protected int tipoComunicazione;
    @XmlElement(name = "ProtocolloTelematicoDaSostituire")
    protected String protocolloTelematicoDaSostituire;

    /**
     * Gets the value of the codiceFornitura property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCodiceFornitura() {
        return codiceFornitura;
    }

    /**
     * Sets the value of the codiceFornitura property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCodiceFornitura(String value) {
        this.codiceFornitura = value;
    }

    /**
     * Gets the value of the periodoImposta property.
     * 
     */
    public int getPeriodoImposta() {
        return periodoImposta;
    }

    /**
     * Sets the value of the periodoImposta property.
     * 
     */
    public void setPeriodoImposta(int value) {
        this.periodoImposta = value;
    }

    /**
     * Gets the value of the tipoComunicazione property.
     * 
     */
    public int getTipoComunicazione() {
        return tipoComunicazione;
    }

    /**
     * Sets the value of the tipoComunicazione property.
     * 
     */
    public void setTipoComunicazione(int value) {
        this.tipoComunicazione = value;
    }

    /**
     * Gets the value of the protocolloTelematicoDaSostituire property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProtocolloTelematicoDaSostituire() {
        return protocolloTelematicoDaSostituire;
    }

    /**
     * Sets the value of the protocolloTelematicoDaSostituire property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProtocolloTelematicoDaSostituire(String value) {
        this.protocolloTelematicoDaSostituire = value;
    }

}
