//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.27 at 11:03:36 AM CET 
//


package org.sinekarta.alfresco.model.agenziaEntrate;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}Numero"/>
 *         &lt;element ref="{}DataInizioVal"/>
 *         &lt;element ref="{}DataFineVal"/>
 *       &lt;/sequence>
 *       &lt;attribute name="TipoDocumento" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="FattureEmesse"/>
 *             &lt;enumeration value="FattureRicevute"/>
 *             &lt;enumeration value="NotaVariazioneAumento"/>
 *             &lt;enumeration value="NotaVariazioneDiminuzione"/>
 *             &lt;enumeration value="DocumTrasporto"/>
 *             &lt;enumeration value="Scontrino"/>
 *             &lt;enumeration value="Ricevuta"/>
 *             &lt;enumeration value="Bolla"/>
 *             &lt;enumeration value="LibroGiornale"/>
 *             &lt;enumeration value="LibroInventari"/>
 *             &lt;enumeration value="LibroMastro"/>
 *             &lt;enumeration value="RegistroCronologico"/>
 *             &lt;enumeration value="LibroCespiti"/>
 *             &lt;enumeration value="RegistroIrpef"/>
 *             &lt;enumeration value="RegistroFattureAcquisto"/>
 *             &lt;enumeration value="RegistroAcquistiAgenzieViaggio"/>
 *             &lt;enumeration value="RegistroFattureEmesse"/>
 *             &lt;enumeration value="RegistroFattureInSospeso"/>
 *             &lt;enumeration value="RegistroCorrispettivi"/>
 *             &lt;enumeration value="GiornaleFondo"/>
 *             &lt;enumeration value="RegistroCorrispettiviAgenzieViaggio"/>
 *             &lt;enumeration value="RegistroEmergenzaIva"/>
 *             &lt;enumeration value="Bollettario"/>
 *             &lt;enumeration value="RegistroPrimaNota"/>
 *             &lt;enumeration value="RegistroUnicoIva"/>
 *             &lt;enumeration value="RegistroRiepilogativoIva"/>
 *             &lt;enumeration value="RegistroSezionaleIvaAcquisitiIntraUe"/>
 *             &lt;enumeration value="RegistroAcquistiIntraUeNonComm"/>
 *             &lt;enumeration value="RegistroTrasferimentiIntraUe"/>
 *             &lt;enumeration value="RegistroDichIntentiEmesse"/>
 *             &lt;enumeration value="RegistroDichIntentiRicevute"/>
 *             &lt;enumeration value="RegistroOmaggi"/>
 *             &lt;enumeration value="RegistroMemoriaProdContrassegno"/>
 *             &lt;enumeration value="RegistroLavorazioneProdContrassegno"/>
 *             &lt;enumeration value="RegistroCaricoProdContrassegno"/>
 *             &lt;enumeration value="RegistroScaricoProdContrassegno"/>
 *             &lt;enumeration value="RegistroBeniInDeposito"/>
 *             &lt;enumeration value="RegistroBeniInContoLavorazione"/>
 *             &lt;enumeration value="RegistroBeniComodato"/>
 *             &lt;enumeration value="RegistroBeniProva"/>
 *             &lt;enumeration value="RegistroSezionaleIvaInterno"/>
 *             &lt;enumeration value="RegistroCaricoStampatiFiscali"/>
 *             &lt;enumeration value="RegistroSocControllantiControllate"/>
 *             &lt;enumeration value="RegistroCaricoScaricoRegimeMargineMetodoAnalitico"/>
 *             &lt;enumeration value="RegistroAcquistiRegimeMargineMetodoGlobale"/>
 *             &lt;enumeration value="RegistroVenditeRegimeMargineMetodoGlobale"/>
 *             &lt;enumeration value="RegistroCaricoCentriElabDati"/>
 *             &lt;enumeration value="RegistroScaricoCentriElabDati"/>
 *             &lt;enumeration value="RegistroSommeRicevuteDeposito"/>
 *             &lt;enumeration value="RegistroEditori"/>
 *             &lt;enumeration value="LibroSoci"/>
 *             &lt;enumeration value="LibroObbligazioni"/>
 *             &lt;enumeration value="LibroAdunanzeDelibAssemblee"/>
 *             &lt;enumeration value="LibroAdunanzeDelibConsiglioAmministrazione"/>
 *             &lt;enumeration value="LibroAdunanzeDelibCollegioSindacale"/>
 *             &lt;enumeration value="LibroAdunanzeDelibComitatoEsecutivo"/>
 *             &lt;enumeration value="LibroAdunanzeDelibAssembleeAzionisti"/>
 *             &lt;enumeration value="AltriRegistri"/>
 *             &lt;enumeration value="UnicoPersoneFisiche"/>
 *             &lt;enumeration value="UnicoSocietaPersone"/>
 *             &lt;enumeration value="UnicoSocietaCapitale"/>
 *             &lt;enumeration value="UnicoEntiNonCommerciali"/>
 *             &lt;enumeration value="IrapPersoneFisiche"/>
 *             &lt;enumeration value="IrapSocietaPersone"/>
 *             &lt;enumeration value="IrapSocietaCapitale"/>
 *             &lt;enumeration value="IrapEntiNonCommercialiEdEquiparati"/>
 *             &lt;enumeration value="IrapAmministrazioniEdEntiPubblici"/>
 *             &lt;enumeration value="Modello730"/>
 *             &lt;enumeration value="ModelloConsolidatoNazionaleEMondiale"/>
 *             &lt;enumeration value="ModelloIva"/>
 *             &lt;enumeration value="ModelloIvaVrRichiestaRimborsoCreditoIva"/>
 *             &lt;enumeration value="ModelloIva26Lp2006ProspettoLiquidazioniPeriodiche"/>
 *             &lt;enumeration value="ModelloIva74Bis"/>
 *             &lt;enumeration value="ComunicazioneAnnualeDatiIva"/>
 *             &lt;enumeration value="ModelloRichiestaRimborsoCreditoIvaTrimestrale"/>
 *             &lt;enumeration value="ModelloDatiContenutiDichiarazioneIntentoRicevute"/>
 *             &lt;enumeration value="Modello770Semplificato"/>
 *             &lt;enumeration value="Modello770Ordinario"/>
 *             &lt;enumeration value="ModelloCertificazioneCud"/>
 *             &lt;enumeration value="ModelloF23"/>
 *             &lt;enumeration value="ModelloF24"/>
 *             &lt;enumeration value="ModelliAllegatiDichiarazioneRedditiModelloUnico"/>
 *             &lt;enumeration value="ModelliAnnotazioneSeparata"/>
 *             &lt;enumeration value="RicevutaPresentazioneModelliDichiarazione"/>
 *             &lt;enumeration value="AltriDocumenti"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "numero",
    "dataInizioVal",
    "dataFineVal"
})
@XmlRootElement(name = "Documento")
public class Documento implements Serializable {

	private static final long serialVersionUID = 1L;
	
    @XmlElement(name = "Numero")
    protected long numero;
    @XmlElement(name = "DataInizioVal", required = true)
    protected DataInizioVal dataInizioVal;
    @XmlElement(name = "DataFineVal", required = true)
    protected DataFineVal dataFineVal;
    @XmlAttribute(name = "TipoDocumento", required = true)
    protected String tipoDocumento;

    /**
     * Gets the value of the numero property.
     * 
     */
    public long getNumero() {
        return numero;
    }

    /**
     * Sets the value of the numero property.
     * 
     */
    public void setNumero(long value) {
        this.numero = value;
    }

    /**
     * Gets the value of the dataInizioVal property.
     * 
     * @return
     *     possible object is
     *     {@link DataInizioVal }
     *     
     */
    public DataInizioVal getDataInizioVal() {
        return dataInizioVal;
    }

    /**
     * Sets the value of the dataInizioVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataInizioVal }
     *     
     */
    public void setDataInizioVal(DataInizioVal value) {
        this.dataInizioVal = value;
    }

    /**
     * Gets the value of the dataFineVal property.
     * 
     * @return
     *     possible object is
     *     {@link DataFineVal }
     *     
     */
    public DataFineVal getDataFineVal() {
        return dataFineVal;
    }

    /**
     * Sets the value of the dataFineVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataFineVal }
     *     
     */
    public void setDataFineVal(DataFineVal value) {
        this.dataFineVal = value;
    }

    /**
     * Gets the value of the tipoDocumento property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTipoDocumento() {
        return tipoDocumento;
    }

    /**
     * Sets the value of the tipoDocumento property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTipoDocumento(String value) {
        this.tipoDocumento = value;
    }

}
