//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-558 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.11.27 at 11:03:36 AM CET 
//


package org.sinekarta.alfresco.model.agenziaEntrate;

import java.io.Serializable;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the org.sinekarta.alfresco.model.agenziaEntrate package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory implements Serializable {

	private static final long serialVersionUID = 1L;
	
    private final static QName _NumIscrizioneAlboCaf_QNAME = new QName("", "NumIscrizioneAlboCaf");
    private final static QName _SiglaProvincia_QNAME = new QName("", "SiglaProvincia");
    private final static QName _CodFisc_QNAME = new QName("", "CodFisc");
    private final static QName _SoggettoObbligatoTrasmissione_QNAME = new QName("", "SoggettoObbligatoTrasmissione");
    private final static QName _Denominazione_QNAME = new QName("", "Denominazione");
    private final static QName _FrazioneVia_QNAME = new QName("", "FrazioneVia");
    private final static QName _Mese_QNAME = new QName("", "Mese");
    private final static QName _ProtocolloTelematicoDaSostituire_QNAME = new QName("", "ProtocolloTelematicoDaSostituire");
    private final static QName _Cap_QNAME = new QName("", "Cap");
    private final static QName _ComuneStato_QNAME = new QName("", "ComuneStato");
    private final static QName _PeriodoImposta_QNAME = new QName("", "PeriodoImposta");
    private final static QName _Impronta_QNAME = new QName("", "Impronta");
    private final static QName _Cognome_QNAME = new QName("", "Cognome");
    private final static QName _ImpegnoTrasmissione_QNAME = new QName("", "ImpegnoTrasmissione");
    private final static QName _Anno_QNAME = new QName("", "Anno");
    private final static QName _Numero_QNAME = new QName("", "Numero");
    private final static QName _DatiResponsabileConservazione_QNAME = new QName("", "DatiResponsabileConservazione");
    private final static QName _TipoComunicazione_QNAME = new QName("", "TipoComunicazione");
    private final static QName _CodiceFornitura_QNAME = new QName("", "CodiceFornitura");
    private final static QName _Sesso_QNAME = new QName("", "Sesso");
    private final static QName _FatturazioneElettronica_QNAME = new QName("", "FatturazioneElettronica");
    private final static QName _NumElemIndice_QNAME = new QName("", "NumElemIndice");
    private final static QName _DatiDelegatoConservazione_QNAME = new QName("", "DatiDelegatoConservazione");
    private final static QName _MarcaTemporale_QNAME = new QName("", "MarcaTemporale");
    private final static QName _NumeroCivico_QNAME = new QName("", "NumeroCivico");
    private final static QName _Nome_QNAME = new QName("", "Nome");
    private final static QName _Giorno_QNAME = new QName("", "Giorno");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: org.sinekarta.alfresco.model.agenziaEntrate
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DatiIntermediarioTrasmissione }
     * 
     */
    public DatiIntermediarioTrasmissione createDatiIntermediarioTrasmissione() {
        return new DatiIntermediarioTrasmissione();
    }

    /**
     * Create an instance of {@link DatiPersonaFisica }
     * 
     */
    public DatiPersonaFisica createDatiPersonaFisica() {
        return new DatiPersonaFisica();
    }

    /**
     * Create an instance of {@link Documento }
     * 
     */
    public Documento createDocumento() {
        return new Documento();
    }

    /**
     * Create an instance of {@link IndiceDocumentiInArchivio }
     * 
     */
    public IndiceDocumentiInArchivio createIndiceDocumentiInArchivio() {
        return new IndiceDocumentiInArchivio();
    }

    /**
     * Create an instance of {@link DomFiscaleSedeLegale }
     * 
     */
    public DomFiscaleSedeLegale createDomFiscaleSedeLegale() {
        return new DomFiscaleSedeLegale();
    }

    /**
     * Create an instance of {@link DatiTitolareContabilita }
     * 
     */
    public DatiTitolareContabilita createDatiTitolareContabilita() {
        return new DatiTitolareContabilita();
    }

    /**
     * Create an instance of {@link Indirizzo }
     * 
     */
    public Indirizzo createIndirizzo() {
        return new Indirizzo();
    }

    /**
     * Create an instance of {@link LuogoConservazione }
     * 
     */
    public LuogoConservazione createLuogoConservazione() {
        return new LuogoConservazione();
    }

    /**
     * Create an instance of {@link DataImpegno }
     * 
     */
    public DataImpegno createDataImpegno() {
        return new DataImpegno();
    }

    /**
     * Create an instance of {@link DatiTrasmissione }
     * 
     */
    public DatiTrasmissione createDatiTrasmissione() {
        return new DatiTrasmissione();
    }

    /**
     * Create an instance of {@link DataFineVal }
     * 
     */
    public DataFineVal createDataFineVal() {
        return new DataFineVal();
    }

    /**
     * Create an instance of {@link Comunicazione }
     * 
     */
    public Comunicazione createComunicazione() {
        return new Comunicazione();
    }

    /**
     * Create an instance of {@link Delegati }
     * 
     */
    public Delegati createDelegati() {
        return new Delegati();
    }

    /**
     * Create an instance of {@link DatiNascita }
     * 
     */
    public DatiNascita createDatiNascita() {
        return new DatiNascita();
    }

    /**
     * Create an instance of {@link DataInizioVal }
     * 
     */
    public DataInizioVal createDataInizioVal() {
        return new DataInizioVal();
    }

    /**
     * Create an instance of {@link DatiFornitura }
     * 
     */
    public DatiFornitura createDatiFornitura() {
        return new DatiFornitura();
    }

    /**
     * Create an instance of {@link DatiAnagrType }
     * 
     */
    public DatiAnagrType createDatiAnagrType() {
        return new DatiAnagrType();
    }

    /**
     * Create an instance of {@link Data }
     * 
     */
    public Data createData() {
        return new Data();
    }

    /**
     * Create an instance of {@link DatiArchivioInformatico }
     * 
     */
    public DatiArchivioInformatico createDatiArchivioInformatico() {
        return new DatiArchivioInformatico();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NumIscrizioneAlboCaf")
    public JAXBElement<Integer> createNumIscrizioneAlboCaf(Integer value) {
        return new JAXBElement<Integer>(_NumIscrizioneAlboCaf_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SiglaProvincia")
    public JAXBElement<String> createSiglaProvincia(String value) {
        return new JAXBElement<String>(_SiglaProvincia_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodFisc")
    public JAXBElement<String> createCodFisc(String value) {
        return new JAXBElement<String>(_CodFisc_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "SoggettoObbligatoTrasmissione")
    public JAXBElement<String> createSoggettoObbligatoTrasmissione(String value) {
        return new JAXBElement<String>(_SoggettoObbligatoTrasmissione_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Denominazione")
    public JAXBElement<String> createDenominazione(String value) {
        return new JAXBElement<String>(_Denominazione_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FrazioneVia")
    public JAXBElement<String> createFrazioneVia(String value) {
        return new JAXBElement<String>(_FrazioneVia_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Mese")
    public JAXBElement<Integer> createMese(Integer value) {
        return new JAXBElement<Integer>(_Mese_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ProtocolloTelematicoDaSostituire")
    public JAXBElement<String> createProtocolloTelematicoDaSostituire(String value) {
        return new JAXBElement<String>(_ProtocolloTelematicoDaSostituire_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cap")
    public JAXBElement<String> createCap(String value) {
        return new JAXBElement<String>(_Cap_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ComuneStato")
    public JAXBElement<String> createComuneStato(String value) {
        return new JAXBElement<String>(_ComuneStato_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "PeriodoImposta")
    public JAXBElement<Integer> createPeriodoImposta(Integer value) {
        return new JAXBElement<Integer>(_PeriodoImposta_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Impronta")
    public JAXBElement<String> createImpronta(String value) {
        return new JAXBElement<String>(_Impronta_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Cognome")
    public JAXBElement<String> createCognome(String value) {
        return new JAXBElement<String>(_Cognome_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "ImpegnoTrasmissione")
    public JAXBElement<Integer> createImpegnoTrasmissione(Integer value) {
        return new JAXBElement<Integer>(_ImpegnoTrasmissione_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Anno")
    public JAXBElement<Integer> createAnno(Integer value) {
        return new JAXBElement<Integer>(_Anno_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Numero")
    public JAXBElement<Long> createNumero(Long value) {
        return new JAXBElement<Long>(_Numero_QNAME, Long.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatiAnagrType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DatiResponsabileConservazione")
    public JAXBElement<DatiAnagrType> createDatiResponsabileConservazione(DatiAnagrType value) {
        return new JAXBElement<DatiAnagrType>(_DatiResponsabileConservazione_QNAME, DatiAnagrType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "TipoComunicazione")
    public JAXBElement<Integer> createTipoComunicazione(Integer value) {
        return new JAXBElement<Integer>(_TipoComunicazione_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "CodiceFornitura")
    public JAXBElement<String> createCodiceFornitura(String value) {
        return new JAXBElement<String>(_CodiceFornitura_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Sesso")
    public JAXBElement<String> createSesso(String value) {
        return new JAXBElement<String>(_Sesso_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "FatturazioneElettronica")
    public JAXBElement<String> createFatturazioneElettronica(String value) {
        return new JAXBElement<String>(_FatturazioneElettronica_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NumElemIndice")
    public JAXBElement<Integer> createNumElemIndice(Integer value) {
        return new JAXBElement<Integer>(_NumElemIndice_QNAME, Integer.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DatiAnagrType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "DatiDelegatoConservazione")
    public JAXBElement<DatiAnagrType> createDatiDelegatoConservazione(DatiAnagrType value) {
        return new JAXBElement<DatiAnagrType>(_DatiDelegatoConservazione_QNAME, DatiAnagrType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "MarcaTemporale")
    public JAXBElement<String> createMarcaTemporale(String value) {
        return new JAXBElement<String>(_MarcaTemporale_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "NumeroCivico")
    public JAXBElement<String> createNumeroCivico(String value) {
        return new JAXBElement<String>(_NumeroCivico_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Nome")
    public JAXBElement<String> createNome(String value) {
        return new JAXBElement<String>(_Nome_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Integer }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "Giorno")
    public JAXBElement<Integer> createGiorno(Integer value) {
        return new JAXBElement<Integer>(_Giorno_QNAME, Integer.class, null, value);
    }

}
